### ISSUE TITLE
Study and research existing Explainable AI framework also find any new frameworks available.

### ISSUE THREAD

**Issue by hemantkshirsagar8** [hemantkshirsagar8/PSL_VNIT_ML_PROJ#1]
Tasks:
- Practice, study and research existing explainable AI framework like LIME, SHAP.
- Research if anything new comes in the market apart from the existing framework.
- Practice its implementation locally.
- Develop ideas to use its techniques in new and existing ML models.

**Comment by hemantkshirsagar8** [comment]
Hows the progress, any difficulties?

**Comment by hemantkshirsagar8** [comment]
- Doubts about Google colab
- Explained with walk through.

**Comment by sathish2379** [comment]
https://blog.dominodatalab.com/shap-lime-python-libraries-part-1-great-explainers-pros-cons/
https://blog.dominodatalab.com/shap-lime-python-libraries-part-2-using-shap-lime/

concludes why SHAP is better than LIME

**Comment by hemantkshirsagar8** [comment]
- Students have prepared PPT presentations and given a demo in meetup 4.
- Roadmap and architectures have been now finalized.
- So we can conclude that learning and research are in direction and we can now focus on individual algorithms work, accordingly.
- As this ticket fulfilled its goals up till now, we can close this ticket.
